services:
  pytorch:
    stdin_open: true
    build:
        context: .
        dockerfile: Dockerfile
    tty: true
    container_name: pytorch
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./src:/root/src
      - ./ComfyUI/:/home/ubuntu/ComfyUI
    command: ["python3", "/home/ubuntu/ComfyUI/main.py", "--normalvram"]
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 20G
    image: rocm/pytorch:latest 
    network_mode: host
